#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SDK_ROOT="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-$ROOT_DIR/.android-sdk}}"
LOCAL_PROPERTIES="$ROOT_DIR/local.properties"

ESCAPED_SDK_DIR="${SDK_ROOT//\/\\}"
ESCAPED_SDK_DIR="${ESCAPED_SDK_DIR//:/\\:}"

cat > "$LOCAL_PROPERTIES" <<EOF
## Auto-generated by .devcontainer/scripts/ensure-local-properties.sh
## Safe to overwrite.
sdk.dir=$ESCAPED_SDK_DIR
EOF

echo "Wrote $LOCAL_PROPERTIES with sdk.dir=$SDK_ROOT"
